In [1]:

import logging
import importlib
importlib.reload(logging) # see https://stackoverflow.com/a/21475297/1469195
log = logging.getLogger()
log.setLevel('DEBUG')
import sys
logging.basicConfig(format='%(asctime)s %(levelname)s : %(message)s',
                     level=logging.DEBUG, stream=sys.stdout)

import os
os.sys.path.append('/home/schirrmr/braindecode/code/fbcsp/')
os.sys.path.append('/home/schirrmr/braindecode/code/braindecode/')

%load_ext autoreload
%autoreload 2
%cd /home/schirrmr/

import matplotlib
%matplotlib inline
%config InlineBackend.figure_format = 'svg' 
matplotlib.rcParams['figure.figsize'] = (12.0, 1.0)
matplotlib.rcParams['font.size'] = 7

import logging
log = logging.getLogger()
log.setLevel('DEBUG')

/home/schirrmr


In [ ]:
from braindecode.datasets.bbci import BBCIDataset
set_loader = BBCIDataset('data/BBCI-RGO-Error/MaGlRGO1_1-7.BBCI.mat',
                        load_sensor_names=['C3', 'C4', 'C1', 'C2', 'CPz', 'F3', 'F4', 'Fz'])
cnt = set_loader.load()
cnt = cnt.drop_channels(['STI 014'])

In [4]:
eog_cnt = BBCIDataset('data/BBCI-RGO-Error/MaGlRGO1_1-7.BBCI.mat',
                        load_sensor_names=['EOG_L', 'EOG_R', 'EOG_U', 'EOG_D',]).load()
eog_cnt = eog_cnt.drop_channels(['STI 014'])

Creating RawArray with float64 data, n_channels=4, n_times=7960276
    Range : 0 ... 7960275 =      0.000 ...  7960.275 secs
Ready.
2017-09-21 16:05:27,282 WARNING : Same sample has at least two markers.
37195: (222 and 17).
Marker codes will be summed.
2017-09-21 16:05:27,283 WARNING : Same sample has at least two markers.
59168: (211 and 1).
Marker codes will be summed.
2017-09-21 16:05:27,284 WARNING : Same sample has at least two markers.
69681: (111 and 24).
Marker codes will be summed.
2017-09-21 16:05:27,285 WARNING : Same sample has at least two markers.
80612: (112 and 33).
Marker codes will be summed.
2017-09-21 16:05:27,286 WARNING : Same sample has at least two markers.
93355: (111 and 21).
Marker codes will be summed.
2017-09-21 16:05:27,286 WARNING : Same sample has at least two markers.
106201: (222 and 16).
Marker codes will be summed.
2017-09-21 16:05:27,287 WARNING : Same sample has at least two markers.
119662: (222 and 20).
Marker codes will be summed.
2017-09-21 16

2017-09-21 16:05:27,332 WARNING : Same sample has at least two markers.
884655: (221 and 9).
Marker codes will be summed.
2017-09-21 16:05:27,333 WARNING : Same sample has at least two markers.
895301: (121 and 30).
Marker codes will be summed.
2017-09-21 16:05:27,333 WARNING : Same sample has at least two markers.
906180: (211 and 5).
Marker codes will be summed.
2017-09-21 16:05:27,334 WARNING : Same sample has at least two markers.
930005: (111 and 21).
Marker codes will be summed.
2017-09-21 16:05:27,335 WARNING : Same sample has at least two markers.
940851: (111 and 22).
Marker codes will be summed.
2017-09-21 16:05:27,336 WARNING : Same sample has at least two markers.
951413: (221 and 8).
Marker codes will be summed.
2017-09-21 16:05:27,336 WARNING : Same sample has at least two markers.
982947: (121 and 27).
Marker codes will be summed.
2017-09-21 16:05:27,337 WARNING : Same sample has at least two markers.
994542: (212 and 12).
Marker codes will be summed.
2017-09-21 16:05:27

2017-09-21 16:05:27,382 WARNING : Same sample has at least two markers.
1895821: (222 and 18).
Marker codes will be summed.
2017-09-21 16:05:27,382 WARNING : Same sample has at least two markers.
1906667: (122 and 38).
Marker codes will be summed.
2017-09-21 16:05:27,383 WARNING : Same sample has at least two markers.
1917746: (121 and 30).
Marker codes will be summed.
2017-09-21 16:05:27,384 WARNING : Same sample has at least two markers.
1930224: (122 and 37).
Marker codes will be summed.
2017-09-21 16:05:27,385 WARNING : Same sample has at least two markers.
1941554: (121 and 29).
Marker codes will be summed.
2017-09-21 16:05:27,385 WARNING : Same sample has at least two markers.
1952766: (112 and 35).
Marker codes will be summed.
2017-09-21 16:05:27,386 WARNING : Same sample has at least two markers.
1977340: (112 and 32).
Marker codes will be summed.
2017-09-21 16:05:27,387 WARNING : Same sample has at least two markers.
1988236: (211 and 1).
Marker codes will be summed.
2017-09-2

2017-09-21 16:05:27,431 WARNING : Same sample has at least two markers.
3061183: (211 and 5).
Marker codes will be summed.
2017-09-21 16:05:27,432 WARNING : Same sample has at least two markers.
3073595: (211 and 3).
Marker codes will be summed.
2017-09-21 16:05:27,433 WARNING : Same sample has at least two markers.
3086057: (112 and 33).
Marker codes will be summed.
2017-09-21 16:05:27,433 WARNING : Same sample has at least two markers.
3098286: (222 and 18).
Marker codes will be summed.
2017-09-21 16:05:27,434 WARNING : Same sample has at least two markers.
3109182: (111 and 22).
Marker codes will be summed.
2017-09-21 16:05:27,435 WARNING : Same sample has at least two markers.
3120178: (222 and 17).
Marker codes will be summed.
2017-09-21 16:05:27,436 WARNING : Same sample has at least two markers.
3131790: (221 and 10).
Marker codes will be summed.
2017-09-21 16:05:27,436 WARNING : Same sample has at least two markers.
3144285: (221 and 6).
Marker codes will be summed.
2017-09-21 

2017-09-21 16:05:27,485 WARNING : Same sample has at least two markers.
3971444: (221 and 7).
Marker codes will be summed.
2017-09-21 16:05:27,511 WARNING : Same sample has at least two markers.
3983789: (122 and 36).
Marker codes will be summed.
2017-09-21 16:05:27,512 WARNING : Same sample has at least two markers.
3996134: (222 and 20).
Marker codes will be summed.
2017-09-21 16:05:27,568 WARNING : Same sample has at least two markers.
4007397: (121 and 27).
Marker codes will be summed.
2017-09-21 16:05:27,569 WARNING : Same sample has at least two markers.
4019859: (121 and 28).
Marker codes will be summed.
2017-09-21 16:05:27,569 WARNING : Same sample has at least two markers.
4044449: (222 and 17).
Marker codes will be summed.
2017-09-21 16:05:27,570 WARNING : Same sample has at least two markers.
4067907: (212 and 12).
Marker codes will be summed.
2017-09-21 16:05:27,571 WARNING : Same sample has at least two markers.
4078920: (112 and 34).
Marker codes will be summed.
2017-09-2

2017-09-21 16:05:27,704 WARNING : Same sample has at least two markers.
4942789: (211 and 3).
Marker codes will be summed.
2017-09-21 16:05:27,705 WARNING : Same sample has at least two markers.
4954501: (111 and 21).
Marker codes will be summed.
2017-09-21 16:05:27,706 WARNING : Same sample has at least two markers.
4967179: (212 and 13).
Marker codes will be summed.
2017-09-21 16:05:27,706 WARNING : Same sample has at least two markers.
4978475: (212 and 12).
Marker codes will be summed.
2017-09-21 16:05:27,707 WARNING : Same sample has at least two markers.
4990471: (222 and 20).
Marker codes will be summed.
2017-09-21 16:05:27,708 WARNING : Same sample has at least two markers.
5001383: (112 and 33).
Marker codes will be summed.
2017-09-21 16:05:27,709 WARNING : Same sample has at least two markers.
5012379: (112 and 31).
Marker codes will be summed.
2017-09-21 16:05:27,710 WARNING : Same sample has at least two markers.
5024391: (212 and 14).
Marker codes will be summed.
2017-09-2

2017-09-21 16:05:27,760 WARNING : Same sample has at least two markers.
5816810: (122 and 37).
Marker codes will be summed.
2017-09-21 16:05:27,761 WARNING : Same sample has at least two markers.
5828189: (111 and 21).
Marker codes will be summed.
2017-09-21 16:05:27,761 WARNING : Same sample has at least two markers.
5839918: (211 and 4).
Marker codes will be summed.
2017-09-21 16:05:27,762 WARNING : Same sample has at least two markers.
5862310: (222 and 17).
Marker codes will be summed.
2017-09-21 16:05:27,763 WARNING : Same sample has at least two markers.
5874056: (112 and 32).
Marker codes will be summed.
2017-09-21 16:05:27,764 WARNING : Same sample has at least two markers.
5885751: (112 and 33).
Marker codes will be summed.
2017-09-21 16:05:27,765 WARNING : Same sample has at least two markers.
5957907: (221 and 8).
Marker codes will be summed.
2017-09-21 16:05:27,766 WARNING : Same sample has at least two markers.
5969353: (221 and 9).
Marker codes will be summed.
2017-09-21 

Marker codes will be summed.
2017-09-21 16:05:27,813 WARNING : Same sample has at least two markers.
6707514: (212 and 13).
Marker codes will be summed.
2017-09-21 16:05:27,814 WARNING : Same sample has at least two markers.
6719593: (112 and 35).
Marker codes will be summed.
2017-09-21 16:05:27,815 WARNING : Same sample has at least two markers.
6730072: (222 and 20).
Marker codes will be summed.
2017-09-21 16:05:27,815 WARNING : Same sample has at least two markers.
6740935: (111 and 21).
Marker codes will be summed.
2017-09-21 16:05:27,816 WARNING : Same sample has at least two markers.
6752747: (222 and 18).
Marker codes will be summed.
2017-09-21 16:05:27,817 WARNING : Same sample has at least two markers.
6763609: (122 and 36).
Marker codes will be summed.
2017-09-21 16:05:27,818 WARNING : Same sample has at least two markers.
6775905: (212 and 15).
Marker codes will be summed.
2017-09-21 16:05:27,818 WARNING : Same sample has at least two markers.
6787201: (121 and 27).
Marker c

Marker codes will be summed.
2017-09-21 16:05:27,866 WARNING : Same sample has at least two markers.
7606643: (212 and 11).
Marker codes will be summed.
2017-09-21 16:05:27,867 WARNING : Same sample has at least two markers.
7618089: (112 and 33).
Marker codes will be summed.
2017-09-21 16:05:27,868 WARNING : Same sample has at least two markers.
7628968: (122 and 40).
Marker codes will be summed.
2017-09-21 16:05:27,869 WARNING : Same sample has at least two markers.
7641780: (112 and 35).
Marker codes will be summed.
2017-09-21 16:05:27,869 WARNING : Same sample has at least two markers.
7652626: (222 and 16).
Marker codes will be summed.
2017-09-21 16:05:27,870 WARNING : Same sample has at least two markers.
7663222: (122 and 36).
Marker codes will be summed.
2017-09-21 16:05:27,871 WARNING : Same sample has at least two markers.
7675434: (221 and 8).
Marker codes will be summed.
2017-09-21 16:05:27,872 WARNING : Same sample has at least two markers.
7686463: (212 and 13).
Marker co

In [16]:
from braindecode.mne_ext.signalproc import mne_apply, resample_cnt
from braindecode.datautil.signalproc import bandpass_cnt

import numpy as np

def car_cnt(cnt):
    return mne_apply(lambda x: x - np.mean(x,axis=0, keepdims=True), cnt)

cnt = resample_cnt(cnt,500)
cnt = car_cnt(cnt)
cnt = mne_apply(lambda x: bandpass_cnt(x, 0.5,150.0, cnt.info['sfreq']), cnt)

2017-09-21 16:07:10,776 WARNING : This is not causal, uses future data....
2017-09-21 16:07:10,777 INFO : Resampling from 1000.000000 to 500.000000 Hz.
Creating RawArray with float64 data, n_channels=8, n_times=3980138
    Range : 0 ... 3980137 =      0.000 ...  7960.274 secs
Ready.


In [20]:
from fbcsp.experiment import CSPExperiment
from collections import OrderedDict
name_to_start_codes = OrderedDict([('Correct', [1,2,5,6,7,11,12,13,15,16,24,25,27,28,30]),
                                  ('Error', [3,4,8,9,10,14,17,18,19,20,21,22,23,26,29])])
epoch_ival_ms = [3300,7500]

In [21]:
from fbcsp.clean import EOGMaxMinCleaner, VarCleaner, apply_multiple_cleaners


cleaners = [EOGMaxMinCleaner(eog_cnt, epoch_ival_ms, name_to_start_codes, threshold=600),
           VarCleaner(whisker_percent=10, whisker_length=3)]
cleaned_cnt = apply_multiple_cleaners(cnt, epoch_ival_ms, name_to_start_codes, cleaners)

2017-09-21 16:08:25,583 INFO : Apply EOGMaxMinCleaner...
2017-09-21 16:08:25,584 INFO : Cleaning...
2017-09-21 16:08:25,916 INFO : Trial per class:
Counter({'Error': 225, 'Correct': 224})
2017-09-21 16:08:26,256 INFO : Trial per class:
Counter({'Error': 225, 'Correct': 224})
2017-09-21 16:08:26,272 INFO : Rejected channels: []
2017-09-21 16:08:26,273 INFO : #Clean trials:     414
2017-09-21 16:08:26,274 INFO : #Rejected trials:  35
2017-09-21 16:08:26,275 INFO : Fraction Clean:    92.2%
2017-09-21 16:08:27,695 INFO : Apply VarCleaner...
2017-09-21 16:08:27,696 INFO : Cleaning...
2017-09-21 16:08:28,544 INFO : Trial per class:
Counter({'Error': 207, 'Correct': 207})
2017-09-21 16:08:28,577 INFO : Rejected channels: []
2017-09-21 16:08:28,578 INFO : #Clean trials:     387
2017-09-21 16:08:28,578 INFO : #Rejected trials:  27
2017-09-21 16:08:28,579 INFO : Fraction Clean:    93.5%


In [23]:
exp = CSPExperiment(cleaned_cnt, name_to_start_codes, epoch_ival_ms,
                    min_freq = 0,
                    max_freq=36,#144, 
                    last_low_freq=30,
                    low_width=2,
                    high_width=6,
                    low_overlap=0,
                    high_overlap=0,
                    filt_order=3,
                    n_folds=10,
                    n_top_bottom_csp_filters=5,
                    n_selected_filterbands=None,
                    n_selected_features=20,
                    forward_steps=2,
                    backward_steps=1,)

In [24]:
from braindecode.datautil.trial_segment import create_signal_target, create_signal_target_from_raw_mne

from braindecode.datautil.signalproc import bandpass_cnt

from braindecode.datautil.iterators import get_balanced_batches

In [25]:
exp.run()

2017-09-21 16:08:37,115 INFO : Trial per class:
Counter({'Error': 195, 'Correct': 192})
2017-09-21 16:08:37,125 INFO : Running Training...
2017-09-21 16:08:37,126 INFO : Filter 1/17, 0.20 to 1.00 Hz
2017-09-21 16:08:38,712 INFO : Trial per class:
Counter({'Error': 195, 'Correct': 192})
2017-09-21 16:08:38,720 INFO : Fold Nr: 1
2017-09-21 16:08:38,726 INFO : Class 1 vs 2
2017-09-21 16:08:39,174 INFO : Train: 58.33%
2017-09-21 16:08:39,178 INFO : Test:  51.28%
2017-09-21 16:08:39,181 INFO : Fold Nr: 2
2017-09-21 16:08:39,189 INFO : Class 1 vs 2
2017-09-21 16:08:39,625 INFO : Train: 56.32%
2017-09-21 16:08:39,629 INFO : Test:  51.28%
2017-09-21 16:08:39,632 INFO : Fold Nr: 3
2017-09-21 16:08:39,640 INFO : Class 1 vs 2
2017-09-21 16:08:40,089 INFO : Train: 60.92%
2017-09-21 16:08:40,093 INFO : Test:  43.59%
2017-09-21 16:08:40,096 INFO : Fold Nr: 4
2017-09-21 16:08:40,110 INFO : Class 1 vs 2
2017-09-21 16:08:40,559 INFO : Train: 54.60%
2017-09-21 16:08:40,563 INFO : Test:  48.72%
2017-09-2

2017-09-21 16:09:00,356 INFO : Test:  51.28%
2017-09-21 16:09:00,358 INFO : Fold Nr: 3
2017-09-21 16:09:00,364 INFO : Class 1 vs 2
2017-09-21 16:09:00,693 INFO : Train: 57.76%
2017-09-21 16:09:00,694 INFO : Test:  46.15%
2017-09-21 16:09:00,694 INFO : Fold Nr: 4
2017-09-21 16:09:00,701 INFO : Class 1 vs 2
2017-09-21 16:09:01,028 INFO : Train: 58.05%
2017-09-21 16:09:01,029 INFO : Test:  30.77%
2017-09-21 16:09:01,030 INFO : Fold Nr: 5
2017-09-21 16:09:01,036 INFO : Class 1 vs 2
2017-09-21 16:09:01,365 INFO : Train: 56.90%
2017-09-21 16:09:01,366 INFO : Test:  48.72%
2017-09-21 16:09:01,367 INFO : Fold Nr: 6
2017-09-21 16:09:01,374 INFO : Class 1 vs 2
2017-09-21 16:09:01,699 INFO : Train: 54.60%
2017-09-21 16:09:01,700 INFO : Test:  46.15%
2017-09-21 16:09:01,701 INFO : Fold Nr: 7
2017-09-21 16:09:01,707 INFO : Class 1 vs 2
2017-09-21 16:09:02,039 INFO : Train: 57.47%
2017-09-21 16:09:02,041 INFO : Test:  41.03%
2017-09-21 16:09:02,041 INFO : Fold Nr: 8
2017-09-21 16:09:02,048 INFO : Cl

2017-09-21 16:09:22,114 INFO : Fold Nr: 6
2017-09-21 16:09:22,120 INFO : Class 1 vs 2
2017-09-21 16:09:22,445 INFO : Train: 56.03%
2017-09-21 16:09:22,446 INFO : Test:  48.72%
2017-09-21 16:09:22,447 INFO : Fold Nr: 7
2017-09-21 16:09:22,453 INFO : Class 1 vs 2
2017-09-21 16:09:22,779 INFO : Train: 58.62%
2017-09-21 16:09:22,780 INFO : Test:  48.72%
2017-09-21 16:09:22,781 INFO : Fold Nr: 8
2017-09-21 16:09:22,787 INFO : Class 1 vs 2
2017-09-21 16:09:23,117 INFO : Train: 58.17%
2017-09-21 16:09:23,118 INFO : Test:  50.00%
2017-09-21 16:09:23,118 INFO : Fold Nr: 9
2017-09-21 16:09:23,124 INFO : Class 1 vs 2
2017-09-21 16:09:23,454 INFO : Train: 57.31%
2017-09-21 16:09:23,455 INFO : Test:  57.89%
2017-09-21 16:09:23,456 INFO : Fold Nr: 10
2017-09-21 16:09:23,462 INFO : Class 1 vs 2
2017-09-21 16:09:23,792 INFO : Train: 61.32%
2017-09-21 16:09:23,794 INFO : Test:  36.84%
2017-09-21 16:09:23,795 INFO : Filter 10/17, 17.00 to 19.00 Hz
2017-09-21 16:09:25,337 INFO : Trial per class:
Counter(

2017-09-21 16:09:42,538 INFO : Class 1 vs 2
2017-09-21 16:09:42,851 INFO : Train: 59.89%
2017-09-21 16:09:42,854 INFO : Test:  52.63%
2017-09-21 16:09:42,855 INFO : Fold Nr: 10
2017-09-21 16:09:42,860 INFO : Class 1 vs 2
2017-09-21 16:09:43,210 INFO : Train: 61.89%
2017-09-21 16:09:43,212 INFO : Test:  50.00%
2017-09-21 16:09:43,213 INFO : Filter 14/17, 25.00 to 27.00 Hz
2017-09-21 16:09:44,581 INFO : Trial per class:
Counter({'Error': 195, 'Correct': 192})
2017-09-21 16:09:44,592 INFO : Fold Nr: 1
2017-09-21 16:09:44,598 INFO : Class 1 vs 2
2017-09-21 16:09:44,968 INFO : Train: 57.76%
2017-09-21 16:09:44,970 INFO : Test:  66.67%
2017-09-21 16:09:44,970 INFO : Fold Nr: 2
2017-09-21 16:09:44,976 INFO : Class 1 vs 2
2017-09-21 16:09:45,299 INFO : Train: 59.77%
2017-09-21 16:09:45,300 INFO : Test:  58.97%
2017-09-21 16:09:45,301 INFO : Fold Nr: 3
2017-09-21 16:09:45,308 INFO : Class 1 vs 2
2017-09-21 16:09:45,646 INFO : Train: 59.48%
2017-09-21 16:09:45,647 INFO : Test:  43.59%
2017-09-21

2017-09-21 16:10:31,285 INFO : Test:  56.41%
2017-09-21 16:10:31,286 INFO : Fold Nr: 2
2017-09-21 16:10:31,287 INFO : Class 1 vs 2
2017-09-21 16:10:31,288 INFO : Train: 72.41%
2017-09-21 16:10:31,288 INFO : Test:  56.41%
2017-09-21 16:10:31,289 INFO : Fold Nr: 3
2017-09-21 16:10:31,290 INFO : Class 1 vs 2
2017-09-21 16:10:31,291 INFO : Train: 70.98%
2017-09-21 16:10:31,292 INFO : Test:  51.28%
2017-09-21 16:10:31,293 INFO : Fold Nr: 4
2017-09-21 16:10:31,293 INFO : Class 1 vs 2
2017-09-21 16:10:31,294 INFO : Train: 73.56%
2017-09-21 16:10:31,295 INFO : Test:  46.15%
2017-09-21 16:10:31,296 INFO : Fold Nr: 5
2017-09-21 16:10:31,297 INFO : Class 1 vs 2
2017-09-21 16:10:31,298 INFO : Train: 73.85%
2017-09-21 16:10:31,298 INFO : Test:  46.15%
2017-09-21 16:10:31,299 INFO : Fold Nr: 6
2017-09-21 16:10:31,300 INFO : Class 1 vs 2
2017-09-21 16:10:31,301 INFO : Train: 71.84%
2017-09-21 16:10:31,302 INFO : Test:  53.85%
2017-09-21 16:10:31,302 INFO : Fold Nr: 7
2017-09-21 16:10:31,303 INFO : Cl

In [32]:
np.mean(exp.multi_class.test_accuracy)

0.53771929824561404

In [31]:
np.concatenate(exp.multi_class.test_labels)

array([1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0,

In [30]:
exp.multi_class.test_predicted_labels

array([ array([1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0]),
       array([1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1]),
       array([0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0]),
       array([1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]),
       array([1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0]),
       array([0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1]),
       array([1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1]),
       array([1, 0,